server:
  port: ${PORT:0}
#  servlet:
#    context-path: /users-ws

spring:
  application:
    name: users-ws
  devtools:
    restart:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    datasource:
      platform: org.hibernate.dialect.PostgreSQLDialect
      url: "jdbc:postgresql://localhost:5432/photo_app"
      username: postgres
      password: postgres
      driverClassName: org.postgresql.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings:
#        web-allow-others: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driverClassName: org.h2.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

login:
  url:
    path: /users/login

api:
  url:
    path:
      gateway:
        actuator: /actuator/*
      registration: /users-ws/users/*


management:
  endpoints:
    web:
      exposure:
        include: mappings


