server:
  port: ${PORT:0}
#  servlet:
#    context-path: /users-ws

spring:
  application:
    name: users-ws
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  rabbitmq:
    host: localhost
    port: 15672
    username: user
    password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

token:
  expiration: 846000000 #10 days
  secret: uadfiluiafh8r4f4hlfa9asdf

login:
  url:
    path: /users/login